@BASE = http://localhost:3000
@ID_DA_AREA = 2

### Listar todas as áreas
GET {{BASE}}/areas
Accept: application/json

### Listar serviços por área
GET {{BASE}}/servicos/area/4
Accept: application/json

### Criar uma nova área
POST {{BASE}}/areas
Content-Type: application/json

{
    "nome": "Área de Cabeleireiro",
    "descricao": "Área dedicada a serviços de cabeleireiro."
}

### Criar uma nova área repetida
POST {{BASE}}/areas
Content-Type: application/json

{
    "nome": "Área de Cabeleireiro",
    "descricao": "Teste Área Repetida"
}

### Atualizar uma área existente
PUT {{BASE}}/areas/4
Content-Type: application/json

{
    "nome": "Área de Cabeleireiro",
    "descricao": "Área dedicada a serviços da cabeleireira."
}

### Atualizar uma área inexistente
PUT {{BASE}}/areas/999
Content-Type: application/json

{
    "nome": "Área Inexistente",
    "descricao": "Teste Área Inexistente."
}

### Deletar uma área
DELETE {{BASE}}/areas/4
Accept: application/json

### Deletar uma área inexistente
DELETE {{BASE}}/areas/999
Accept: application/json    