@BASE = http://localhost:3000
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21lIjoiUm9iZXJ0byBBbG1laWRhIiwiZW1haWwiOiJyb2JlcnRvLmFkbWluQGVtYWlsLmNvbSIsInBlcmZpbCI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3ODc4NzAxODcsImV4cCI6MTc4Nzg3Mzc4N30.vC1aV3MiwsCsXpkX3ikpqPsJsyD_cnzzrFg4RcFZA_E

### Login do novo usuário (pegar o token gerado abaixo)
POST {{BASE}}/auth/login
Content-Type: application/json

{
    "email": "admin@agendapi.com",
    "senha_hash": "senha123"
}

### Listar todos os horários bloqueados
GET {{BASE}}/horarios_bloqueados
Authorization: Bearer {{TOKEN}}

### Criar um novo horário bloqueado
POST {{BASE}}/horarios_bloqueados
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "profissional_id": 2,
    "inicio": "2026-07-17T11:00:00",
    "fim": "2026-07-17T12:00:00",
    "motivo": "Folga"
}

### Atualizar um horário bloqueado existente
PUT {{BASE}}/horarios_bloqueados/1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "profissional_id": 2,
    "inicio": "2026-07-17T11:00:00",
    "fim": "2026-07-17T12:00:00",
    "motivo": "Feriado"
}

### Atualizar um horário bloqueado inexistente
PUT {{BASE}}/horarios_bloqueados/999
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "profissional_id": 2,
    "inicio": "2026-07-17T11:00:00",
    "fim": "2026-07-17T12:00:00",
    "motivo": "Folga"
}

### Deletar um horário bloqueado existente
DELETE {{BASE}}/horarios_bloqueados/1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### Deletar um horário bloqueado inexistente
DELETE {{BASE}}/horarios_bloqueados/999
Content-Type: application/json
Authorization: Bearer {{TOKEN}}