@BASE = http://localhost:3000
@ID_DO_SERVICO = 1


### Listar todos os serviços
GET {{BASE}}/servicos
Accept: application/json

### Listar serviços por área
GET {{BASE}}/servicos/area/3
Accept: application/json

### Criar um novo serviço
POST {{BASE}}/servicos
Content-Type: application/json

{
    "area_id": "1",
    "nome": "Corte de Cabelo Masculino",
    "duracao": "30",
    "preco": "25.00"
}

### Atualizar um serviço existente
PUT {{BASE}}/servicos/7
Content-Type: application/json

{
    "area_id": "1",
    "nome": "Unhas de Gel com Nail Art",
    "duracao": "30",
    "preco": "30.00"
}

### Atualizar um serviço inexistente
PUT {{BASE}}/servicos/999
Content-Type: application/json

{
    "area_id": "999",
    "nome": "Serviço Inexistente",
    "duracao": "30",
    "preco": "30.00"
}

### Deletar um serviço
DELETE {{BASE}}/servicos/8
Accept: application/json

### Deletar um serviço inexistente
DELETE {{BASE}}/servicos/999
Accept: application/json

### Teste de campos obrigatórios
POST {{BASE}}/servicos
Content-Type: application/json

{
    "area_id": "1",
    "nome": "Corte de Cabelo Masculino",
    "preco": "25.00"
}