@BASE = http://localhost:3000
@ID_DO_USUARIO = 1

### Listar todos os usuários
GET {{BASE}}/users
Accept: application/json

### Criar um novo usuário
POST {{BASE}}/users
Content-Type: application/json

{
    "nome": "Ana Almeida",
    "email": "ana@email.com",
    "senha_hash": "senha123",
    "perfil": "cliente"
}

### Criar um novo usuário com email inválido
POST {{BASE}}/users
Content-Type: application/json

{
    "nome": "Teste E-mail Inválido",
    "email": "email_invalido",
    "senha_hash": "senha123",
    "perfil": "cliente"
}

### Criar um novo usuário com email repetido
POST {{BASE}}/users
Content-Type: application/json

{
    "nome": "Teste E-mail Repetido",
    "email": "ana@example.com",
    "senha_hash": "senha123",
    "perfil": "cliente"
}

### Atualizar um usuário existente
PUT {{BASE}}/users/{{ID_DO_USUARIO}}
Content-Type: application/json

{
    "nome": "Julio Silva",
    "email": "julio@example.com",
    "senha_hash": "senha123",
    "perfil": "cliente"
}

### Atualizar um usuário inexistente
PUT {{BASE}}/users/999
Content-Type: application/json

{
    "nome": "Usuário Inexistente",
    "email": "inexistente@example.com",
    "senha_hash": "senha123",
    "perfil": "cliente"
}

### Deletar um usuário
DELETE {{BASE}}/users/{{ID_DO_USUARIO}}
Accept: application/json

### Deletar um usuário inexistente
DELETE {{BASE}}/users/999
Accept: application/json    