@BASE = http://localhost:3000
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub21lIjoiUm9iZXJ0byBBbG1laWRhIiwiZW1haWwiOiJyb2JlcnRvLmFkbWluQGVtYWlsLmNvbSIsInBlcmZpbCI6ImFkbWluaXN0cmFkb3IiLCJpYXQiOjE3ODc4NzAxODcsImV4cCI6MTc4Nzg3Mzc4N30.vC1aV3MiwsCsXpkX3ikpqPsJsyD_cnzzrFg4RcFZA_E

### Login do novo usuário (pegar o token gerado abaixo)
POST {{BASE}}/auth/login
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "email": "roberto.admin@email.com",
    "senha_hash": "senha123"
}

### Listar todos os usuários
GET {{BASE}}/users
Accept: application/json
Authorization: Bearer {{TOKEN}}

### Criar um novo usuário
POST {{BASE}}/users
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "nome": "Ana Almeida",
    "email": "ana.almeida2@example.com",
    "senha_hash": "senha123",
    "perfil": "cliente"
}

### Criar um novo usuário com email inválido
POST {{BASE}}/users
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "nome": "Teste E-mail Inválido",
    "email": "email_invalido",
    "senha_hash": "senha123",
    "perfil": "cliente"
}

### Criar um novo usuário com email repetido
POST {{BASE}}/users
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "nome": "Teste E-mail Repetido",
    "email": "ana@example.com",
    "senha_hash": "senha123",
    "perfil": "cliente"
}

### Atualizar um usuário existente
PUT {{BASE}}/users/1
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "nome": "Julio Silva",
    "email": "julio@example.com",
    "senha_hash": "senha123",
    "perfil": "cliente"
}

### Atualizar um usuário inexistente
PUT {{BASE}}/users/999
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "nome": "Usuário Inexistente",
    "email": "inexistente@example.com",
    "senha_hash": "senha123",
    "perfil": "cliente"
}

### Deletar um usuário
DELETE {{BASE}}/users/1
Accept: application/json
Authorization: Bearer {{TOKEN}}

### Deletar um usuário inexistente
DELETE {{BASE}}/users/999
Accept: application/json
Authorization: Bearer {{TOKEN}}  