const express = require("express");
const cors = require("cors");
const authRoute = require("./routes/authRoute");
const publicRoute = require("./routes/publicRoute");
const protectedRoute = require("./routes/protectedRoute");
const helmet = require("helmet");
const serverRoute = require("./routes/serverRoute");
const userRoute = require("./routes/userRoute");
const profissionalRoute = require("./routes/profissionalRoute");
const areaRoute = require("./routes/areaRoute");
const servicoRoute = require("./routes/servicoRoute");
const horarioTrabalhoRoute = require("./routes/horarioTrabalhoRoute");
const statusAgendamentoRoute = require("./routes/statusAgendamentoRoute");
const agendamentoRoute = require("./routes/agendamentoRoute");
const horarioBloqueadoRoute = require("./routes/horarioBloqueadoRoute");
const errorMiddleware = require("./middlewares/errorMiddleware");
const app = express();

app.use(cors());
app.use(helmet());
app.use(express.json());
app.use("/", serverRoute);
app.use("/auth", authRoute);
app.use("/public", publicRoute);
app.use("/protected", protectedRoute);
app.use("/users", userRoute);
app.use("/profissionais", profissionalRoute);
app.use("/areas", areaRoute);
app.use("/servicos", servicoRoute);
app.use("/servicos/:area_id", servicoRoute);
app.use("/horarios_trabalho", horarioTrabalhoRoute);
app.use("/status_agendamento", statusAgendamentoRoute);
app.use("/status_agendamento/:id", statusAgendamentoRoute);
app.use("/agendamentos", agendamentoRoute);
app.use("/agendamentos/:status_id", agendamentoRoute);
app.use("/agendamentos/:profissional_id", agendamentoRoute);
app.use("/agendamentos/disponibilidade", agendamentoRoute);
app.use("/horarios_bloqueados", horarioBloqueadoRoute);
app.use(errorMiddleware);

module.exports = app;